name: Maven CI

on:
  schedule:
    - cron: '42 0 * * 1'
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  pull_request_target:
    types:
      - labeled
    branches:
      - master
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        if: ${{ github.event_name != 'pull_request_target' }}
        with:
          fetch-depth: 0
          persist-credentials: ${{ !startsWith(github.event_name, 'pull_request') }}
      - uses: actions/checkout@v3
        if: ${{ github.event_name == 'pull_request_target' }}
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          persist-credentials: false
      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        if: ${{ github.event_name != 'release' && github.event_name != 'pull_request_target' }}
        uses: github/codeql-action/init@v2
        with:
          languages: java
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
        if: ${{ !startsWith(github.event_name, 'pull_request') }}
      - name: Build with Maven
        run: mvn -B -V -e clean verify
      - name: Unittest Coverage
        if: ${{ github.event_name != 'release' && github.event_name != 'pull_request_target' }}
        run: >
          mvn -B jacoco:report
      - name: Unittest Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          flags: unittests
      - name: Integrationstest Coverage
        if: ${{ github.event_name != 'release' && github.event_name != 'pull_request_target' }}
        run: >
          mvn -B jacoco:report-integration
      - name: Integrationstest Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          flags: integration
      - name: Perform CodeQL Analysis
        if: ${{ github.event_name != 'release' && github.event_name != 'pull_request_target' }}
        uses: github/codeql-action/analyze@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Sonar Report
        if: ${{ !startsWith(github.event_name, 'pull_request') || !github.event.pull_request.head.repo.fork || contains(github.event.pull_request.labels.*.name, 'sonar') }}
        run: >
          if [  "$GITHUB_EVENT_NAME" == "pull_request_target" ]; 
          then 
            export GITHUB_EVENT_NAME=pull_request; 
            export GITHUB_REF=refs/pull/$GITHUB_PULL_REQUEST/merge; 
          fi && 
          mvn -B -e jacoco:report jacoco:report-integration sonar:sonar -Dsonar.organization=jonasrutishauser-github
        env:
          GITHUB_PULL_REQUEST: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ github.token }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
  update-pr:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'sonar') }}
    steps:
      - name: Remove Sonar Label
        uses: peter-murray/remove-labels-action@v1
        with:
          labels: sonar
